name: appBD
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - scikit-learn==1.0.2
      - mlflow>=1.0
      - pandas
      - pymysql
      - apache-airflow
      - protobuf==3.20.*
      - click
      - Sphinx
      - sphinx-autodoc-typehints
      - sphinx-rtd-theme
      - coverage
      - awscli
      - flake8
      - python-dotenv>=0.5.1
      - xgboost
      - scikit-learn
