channels:
- conda-forge
dependencies:
- python=3.9.15
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.1
  - psutil==5.9.4
  - scikit-learn==1.0.2
  - typing-extensions==4.4.0
  - xgboost==1.7.3
name: mlflow-env
